<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXnx0jj8\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXnx0jj8/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXnx0jj8.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXnx0jj8\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXnx0jj8\appProdProjectContainer([
    'container.build_hash' => 'Xnx0jj8',
    'container.build_id' => '32a44ee9',
    'container.build_time' => 1716543056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXnx0jj8');
